### ISSUE TITLE
用在阅读里会莫名其妙的突入8倍速快进那种感觉

### ISSUE THREAD

**Issue by mitomys** [ag2s20150909/TTS#1]
用在阅读里会莫名其妙的突入8倍速快进那种感觉
大佬可以提供上一个版本的tts么？上一个版本就没有这个问题。
而且有时候还会跳过一些段落。

**Comment by ag2s20150909** [comment]
> 用在阅读里会莫名其妙的突入8倍速快进那种感觉
> 大佬可以提供上一个版本的tts么？上一个版本就没有这个问题。
> 而且有时候还会跳过一些段落。

之前的版本可以在这下载：https://github.com/ag2s20150909/TTS/tree/093e3bdf350e335df1bc03cd79a82cb0abc3c74b/release

**Comment by o0HalfLife0o** [comment]
@ag2s20150909 更新9月2号的版本后所有地方都出现朗读语速极快的问题，而上一版本不管是阅读还是地方应用都是正常的

**Comment by mitomys** [comment]
谢谢老哥

HalfLife ***@***.***> 于2021年9月2日周四 下午11:31写道：
