### ISSUE TITLE
[建议]建议增加edge的接口

### ISSUE THREAD

**Issue by ChenyangGao** [ag2s20150909/TTS#104]
我是从 [ms-ra-forwarder](https://github.com/wxxxcxx/ms-ra-forwarder) 这个项目知道的，可以用 Edge 浏览器提供的接口 也可以用 Azure 接口，Azure 的接口，太卡了，而 Edge 浏览器 的接口，倒是完全不卡。
所以，我提一个建议，也提供一下 Edge 浏览器的接口的声音，虽然声音少了一些，而且没有讲话风格可选，但是，丝般顺滑不卡顿。

**Comment by ag2s20150909** [comment]
> 我是从 [ms-ra-forwarder](https://github.com/wxxxcxx/ms-ra-forwarder) 这个项目知道的，可以用 Edge 浏览器提供的接口 也可以用 Azure 接口，Azure 的接口，太卡了，而 Edge 浏览器 的接口，倒是完全不卡。 所以，我提一个建议，也提供一下 Edge 浏览器的接口的声音，虽然声音少了一些，而且没有讲话风格可选，但是，丝般顺滑不卡顿。

预览模式关闭了就是
