### ISSUE TITLE
分句功能與「重」字處理的問題

### ISSUE THREAD

**Issue by chokhocheung** [ag2s20150909/TTS#113]
我留意到源代碼中「使用分句」功能對於「一重」、「二重」…「十重」這詞語有個邏輯把「重」字的替換成chong 2。

不幸的是，如果當前選用的語音是粵語、灣灣、日文或者韓文的話，這個漢語拼音的chong 2就會導致報錯了。

因此，能不能增加個檢查，只有是正在使用普通話（zh-cn）語音時才做這個替換？（粵語和灣灣似乎都不需要類似的替換邏輯，因為它們念這詞語時都能輸出對應chong 2而不是 zhong 4的那發音。）

此外，將來會不會也能支持在dict.txt使用regex，就像「重」字那樣？

**Comment by ag2s20150909** [comment]
新版本已经支持正则表达式
