### ISSUE TITLE
pixel 3[android 12]无法使用

### ISSUE THREAD

**Issue by LonePheasantWarrior** [ag2s20150909/TTS#13]
具体现象就是无法朗读内容，用“静读天下”朗读文章时每一段都是飞快的通过，并且没有任何声音。
在系统TTS设置页面点击“播放示例语音”按钮也没有任何声音。

难受啊，我想听小说大哥[大哥抽烟]

**Comment by LonePheasantWarrior** [comment]
我用谷歌自带的TTS就能播放，虽然难听的一笔吧。我的安卓系统设置应该是没问题的。
我打包的SDK等级是32，符合设备要求。并且我还给手机降级到安卓11，重新为其设置SDK等级重新打包，但是结果都一样QAQ

**Comment by ag2s20150909** [comment]
> 具体现象就是无法朗读内容，用“静读天下”朗读文章时每一段都是飞快的通过，并且没有任何声音。 在系统TTS设置页面点击“播放示例语音”按钮也没有任何声音。
> 
> 难受啊，我想听小说大哥[大哥抽烟]


可能是你打开了自定义语音，并选择到了一个不支持中文的语音了，中文不返回数据，就是这样。

**Comment by LonePheasantWarrior** [comment]
> > 具体现象就是无法朗读内容，用“静读天下”朗读文章时每一段都是飞快的通过，并且没有任何声音。 在系统TTS设置页面点击“播放示例语音”按钮也没有任何声音。
> > 
> > 难受啊，我想听小说大哥[大哥抽烟]
> 
> 
> 可能是你打开了自定义语音，并选择到了一个不支持中文的语音了，中文不返回数据，就是这样。

应该不是，我选择的第一个晓晓，发音风格也是默认。朗读的也是中文内容

**Comment by LonePheasantWarrior** [comment]
> > 具体现象就是无法朗读内容，用“静读天下”朗读文章时每一段都是飞快的通过，并且没有任何声音。 在系统TTS设置页面点击“播放示例语音”按钮也没有任何声音。
> > 
> > 难受啊，我想听小说大哥[大哥抽烟]
> 
> 
> 可能是你打开了自定义语音，并选择到了一个不支持中文的语音了，中文不返回数据，就是这样。

我知道为啥了，我常年开着clash代理，虽然是“规则”模式到但应该还是走了奇怪的网络路线。总之关掉就好了
