### ISSUE TITLE
tts朗读几乎所有声音类似男生

### ISSUE THREAD

**Issue by chenskiro** [ag2s20150909/TTS#140]
系统: Android 12，
手机型号: honor50 se 
系统ui: magicui6.1

尝试使用tts功能进行朗读时，所有声音都非常低沉，尝试卸载重装仍未解决

**Comment by jing332** [comment]
![Screenshot_20221118111520](https://user-images.githubusercontent.com/42014615/209416163-442e2dfe-4217-41bd-b7f8-b8dee5e11576.jpg)
到系统设置里重置音高。

**Comment by chenskiro** [comment]
> ![Screenshot_20221118111520](https://user-images.githubusercontent.com/42014615/209416163-442e2dfe-4217-41bd-b7f8-b8dee5e11576.jpg)
> 到系统设置里重置音高。

经测试，该机型下点击重置语音语调后，仍需要手动往前调整至合适音高，但再次点击重置后则正常
