### ISSUE TITLE
突发无法获取音频，同时无法进行配置

### ISSUE THREAD

**Issue by fatinghenji** [ag2s20150909/TTS#154]
![Screenshot_2023-01-14-00-15-21-68_c8b102ac7b9ff985df9185de5fad84e4](https://user-images.githubusercontent.com/37131177/212367420-dca03e9c-a6fd-49ee-8756-9aaa4d24eba7.jpg)
![Screenshot_2023-01-14-00-14-22-48_c8b102ac7b9ff985df9185de5fad84e4](https://user-images.githubusercontent.com/37131177/212367428-c9277e07-1ead-44f4-af8a-0bc07a65f884.jpg)

**Comment by ysqishandsome** [comment]
有解决方法了吗😋

**Comment by fatinghenji** [comment]
> 有解决方法了吗😋

没用
