### ISSUE TITLE
Unexpected status line: 89e

### ISSUE THREAD

**Issue by thsea** [ag2s20150909/TTS#166]
哦的系统是安卓7.0的,,最近不能使用这个了..出现了下面两个错误
Unexpected status line: 89e
Expected HTTP 101 response but was "200 OK"

**Comment by pencilqaq** [comment]
> 哦的系统是安卓7.0的,,最近不能使用这个了..出现了下面两个错误 Unexpected status line: 89e Expected HTTP 101 response but was "200 OK"

微软关闭了 试用接口 现在只有edge浏览器的接口能用 不支持调整语气

**Comment by thsea** [comment]
原来是这样啊,谢谢你的回答

**Comment by JiangXY98** [comment]
可以用的中文女声：普通话晓晓、普通话晓伊、粤语晓佳、粤语晓曼、台湾晓臻、台湾晓雨。
