### ISSUE TITLE
！！关于台湾省旗帜问题！！

### ISSUE THREAD

**Issue by Misaka-xiaolan** [ag2s20150909/TTS#18]
语音朗读选择列表中，中文（台湾）的旗帜使用不当！希望您能够改进一下方案。

**Comment by 3166265725** [comment]
？不然用什么？五星红旗吗？

**Comment by o0HalfLife0o** [comment]
或者改成文本格式，弃用flag

**Comment by 27Strokes** [comment]
> 语音朗读选择列表中，中文（台湾）的旗帜使用不当！请您立即更改。

支持

**Comment by Misaka-xiaolan** [comment]
> ？不然用什么？五星红旗吗？

现在还没有什么明文规定。但是作为一个中国人，反对分裂，支持统一是应有的政治立场，使用青天白日旗是不合适的。可以换作文字说明。

**Comment by Misaka-xiaolan** [comment]
> ？不然用什么？五星红旗吗？

如果说这个项目是外国人制作的，我也不会说那么多了。

**Comment by PianCat** [comment]
这个问题你应该先去问问微软，为什么不在国家和地区里面把“台湾”写成“中国台湾”

**Comment by Misaka-xiaolan** [comment]
> 

对于微软来说，我们的力量实在是太小了。我也不清楚微软到底是什么立场。但是就我们自身而言，应该从自身做起，更合规地使用地域名称或符号。感谢你的回复 ：)

**Comment by 27Strokes** [comment]
> 

这个问题，要不要先去问问白宫，为什么全世界搞分裂？

**Comment by 27Strokes** [comment]
> 这个问题你应该先去问问微软，为什么不在国家和地区里面把“台湾”写成“中国台湾”

这个问题，要不要先去问问白宫，为什么全世界搞分裂？

**Comment by foxdodo** [comment]
建议改成膏药旗, 蓝绿皆大欢喜🤣
