### ISSUE TITLE
【求助：win10上使用tts朗读pdf、html、word】

### ISSUE THREAD

**Issue by FollowOwn** [ag2s20150909/TTS#3]
问题：edge上默认の晓晓朗读风格只有nature，有些死板、也没办法调音质。
请问，有win10客户端tts 的推荐吗？
           或者edge上如何调整 晓晓tts朗读风格？
谢谢！

**Comment by Bittersweetme** [comment]
> 问题：edge上默认の晓晓朗读风格只有nature，有些死板、也没办法调音质。 请问，有win10 @客户端tts 的推荐吗？ 或者edge上如何调整 晓晓tts朗读风格？ 谢谢！

> ``
