### ISSUE TITLE
更新到最新版后完全不发声

### ISSUE THREAD

**Issue by daofeng2007** [ag2s20150909/TTS#33]
更新到3月20号这个版本后就完全不出声了，不知道什么原因

**Comment by Tu7353OP** [comment]
有可能是你的网络不畅

**Comment by 1731522874** [comment]
应该不是网络的问题吧，更新之后我的也不能用了，换流量，换WiFi，搭梯子都不行

**Comment by Tu7353OP** [comment]
我刚才试了试把梯子关了，就没声音了

**Comment by n0thing2speak** [comment]
我也是今天更新的，无声。。。。 我说软路由，不存在梯子问题吧

**Comment by n0thing2speak** [comment]
> 我也是今天更新的，无声。。。。 我是软路由，不存在梯子问题吧

speech.platform.bing.com 国内部分城市被墙(比如北京河北)，南方城市都还不错，加入到代理列表吧

**Comment by ledong1** [comment]
今天用老版本只读一句话就停了,更新了新版本之后一句话都不读了.. (我在美东应该不存在梯子问题吧..)

**Comment by Allone** [comment]
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>

**Comment by heiha10** [comment]
> speech.platform.bing.co

edge 浏览器正常使用啊。。。。。

> Reference



> > 我也是今天更新的，无声。。。。 我是软路由，不存在梯子问题吧
> 
> speech.platform.bing.com 国内部分城市被墙(比如北京河北)，南方城市都还不错，加入到代理列表吧

edge浏览器正常使用啊，，，就是这个软件不能发声了。

**Comment by n0thing2speak** [comment]
> > speech.platform.bing.co
> 
> edge 浏览器正常使用啊。。。。。
> 
> > Reference
> 
> > > 我也是今天更新的，无声。。。。 我是软路由，不存在梯子问题吧
> > 
> > 
> > speech.platform.bing.com 国内部分城市被墙(比如北京河北)，南方城市都还不错，加入到代理列表吧
> 
> edge浏览器正常使用啊，，，就是这个软件不能发声了。

我这里 是墙了，北京电信，挂梯子就好了

**Comment by ag2s20150909** [comment]
> 今天用老版本只读一句话就停了,更新了新版本之后一句话都不读了.. (我在美东应该不存在梯子问题吧..)

是微软服务端校验严格了，不让发空的Message

**Comment by gkcngk** [comment]
> 今天用老版本只读一句话就停了,更新了新版本之后一句话都不读了.. (我在美东应该不存在梯子问题吧..)

同样问题，然后我更新到这个版本，已解决 TTS/release/TTS_release_v0.2_202203221936.apk

**Comment by heiha10** [comment]
> > > speech.platform.bing.co
> > 
> > 
> > edge 浏览器正常使用啊。。。。。
> > > Reference
> > 
> > 
> > > > 我也是今天更新的，无声。。。。 我是软路由，不存在梯子问题吧
> > > 
> > > 
> > > speech.platform.bing.com 国内部分城市被墙(比如北京河北)，南方城市都还不错，加入到代理列表吧
> > 
> > 
> > edge浏览器正常使用啊，，，就是这个软件不能发声了。
> 
> 我这里 是墙了，北京电信，挂梯子就好了
> 
> 啊更新：现在是service unavailible了

就是昨天有问题，今天就没事了，不知道微软那边服务器抽的啥风。。。我这边河北网通
