### ISSUE TITLE
无法更改默认发音。

### ISSUE THREAD

**Issue by mymine** [ag2s20150909/TTS#4]
无法更改默认发音。只能用晓晓发音！

**Comment by MrWang5201314** [comment]
我使用小米手机，试了很多次，也是这种现象了

**Comment by mymine** [comment]
> 我使用小米手机，试了很多次，也是这种现象了

算了。不用了。用小爱语音引擎也挺好的。

**Comment by ag2s20150909** [comment]
> > 我使用小米手机，试了很多次，也是这种现象了
> 
> 算了。不用了。用小爱语音引擎也挺好的。作者自己用的！

把自定义开关打开，在下面选择就行了。
