### ISSUE TITLE
华为手机无法更改TTS，请问怎么解决

### ISSUE THREAD

**Issue by Looong01** [ag2s20150909/TTS#53]
华为P20，harmonyOS 2.0
安装了之后，然后在系统设置里切换TTS的时候发现点击切换没有反应
然后用阅读软件进行朗读的时候还是系统默认的讯飞
请问有解决办法吗

**Comment by kujin521** [comment]
微软太叼了吧

**Comment by Looong01** [comment]
我问了一下客服，看样子是harmonyOS有了新的接口，需要您适配一下

**Comment by M17764017422** [comment]
#54 这个方法应该可以彻底解决，当然需要阅读软件支持比如 [legado](https://github.com/gedoor/legado)

**Comment by Looong01** [comment]
> 

非常感谢，已经成功了
