### ISSUE TITLE
原先用的是0.2_202109292211.apk版本,使用中语音流畅,我是与Librera pro配合使用的

### ISSUE THREAD

**Issue by ckangpu** [ag2s20150909/TTS#6]
原先用的是0.2_202109292211.apk版本,使用中语音流畅,我是与Librera pro配合使用的.
后更新了多个版本发现在是个问题,都会出现一个同意的问题:就是一行文字读完后会有卡停顿0.5-1秒,更新TTS_release_v0.2_202112251927.apk 也是同意的停顿.之后即会到0.2_202109292211.apk,问题就不存在了.
多个设备测试同意的问题.
                             ----2021/12/27

https://user-images.githubusercontent.com/96708073/147429771-e8805242-d13c-428d-8e33-077dedee4738.mp4

**Comment by ckangpu** [comment]
以下视频是0.2_202109292211.apk版本与Librera pro配合录制的,真是是流畅

https://user-images.githubusercontent.com/96708073/147430188-21e8f101-5261-4734-9a6e-dbb79ac7740d.mp4

**Comment by ag2s20150909** [comment]
Librera pro会在每行末尾加一个空格，新版本已经处理修复。

**Comment by gianozdp** [comment]
修复了吗？

https://user-images.githubusercontent.com/45479533/218042809-5beb80a9-e138-44fb-a446-cca74d487697.mp4

我刚刚安装了最新的apk和最新的Librera pro，还是存在这个问题啊？
