### ISSUE TITLE
新版本纯英文朗读有问题，TTS_release_v0.2_202112271454

### ISSUE THREAD

**Issue by gkcngk** [ag2s20150909/TTS#7]
大神，TTS_release_v0.2_202112271454 版本的纯英文朗读有问题。直接点系统的sample 句子就能听出来错误。好象是首句的第一个单词被拆成了几个字母来朗读，后面的单词就正常。

恢复到TTS_release_v0.2_202112141710 版本问题就消失了，但这一版Android 12闪退。

另外提个意见，纯英文的调用可以让美国Jenny 当默认吗？比较好听一些。

谢谢，祝新年快乐。

**Comment by ag2s20150909** [comment]
新版修复了。

如果要读的内容全是英文的话，
    如果自定义开关处于关闭状态，系统里面设置成英文时会自动切换成英文。
    如果自定义开关处于开启状态，可以直接在下面设置发音人。

单独为英文切换发音需要断开WebSocket然后再重新连接WebSocket，开销太大。

https://github.com/ag2s20150909/TTS/tree/master/release

**Comment by gkcngk** [comment]
感谢，确认纯英文朗读bug 已修复。

设定系统主语言为English US 之后可以调出US Jenny 选项（我之前是English Australia 为主语言所以只出现AU Natasha 唯一选项）

**Comment by gkcngk** [comment]
新年快乐 :)

近几日，通过app 内置更新功能升级到的新版，重新出现英文分段的bug（应该是TTS_release_v0.2_202201291010.apk）
1. 部分情况下会把 it's 这类分拆成 it 和 s 两个部分来读。
2. 引号内的文字会被单独拎出来断句，导致整一串句子的语调比较机械化和停顿点卡在奇怪地方

在升级之前，我使用的版本是在1月1日发布的TTS_release_v0.2_202201011046.apk。现在重新恢复到这个就没问题了断句。
年后有时间请修复一下分段的bug（或者提供一个关闭分段功能的开关？）

**Comment by gkcngk** [comment]
谢谢，更新到[TTS_release_v0.2_202202021453.apk] 后可以使用分段开关避免这个bug
