### ISSUE TITLE
能不能缓存上两三句话

### ISSUE THREAD

**Issue by WeihuaGu** [ag2s20150909/TTS#72]
由于微软网络时好时坏，句子之间停顿时间有点长，有时还出错。有可能缓存上几句话再开始朗读嘛？

**Comment by laulguo** [comment]
确实感觉非常有意义。。。

**Comment by thredreams** [comment]
我看了一下具体实现，这个项目本质上是实现了TTS的service，这个服务只负责合成语音，然后将合成完的音频数据写入给音频播放线程的缓冲池。外部应用调用TTS的时候，是将要合成语音的文字一次性加入合成队列，由TTS引擎从队列中一次一次取出字符串，并调用service合成语音。
而句子之间实质上是两次调用service，在上一句话合成完之后，音频播放线程应该就已经开始朗读了，这个过程应该是和第二句话的合成与接收是同步进行的。我们感觉到的顿挫感是因为音频播放完了，下一句话还没写入缓冲池。
我想到的一个解决方案是，让第一句话尽可能的长，这样就有足够的时间等待下一句话的合成，（因为音频播放速度比合成速度慢）。
如何让第一句话尽可能的长，有两种思路，最方便的是让调用TTS的应用去管理一次合成文字的长度，之所以觉得这个方便是因为从一开始提到的语音合成的流程来看，在TTS的Service中合并多次调用并不妥当。
另一个就是在service中检查本次合成的字符串的长度，如果过短，就等待很短的一个时间，看有没有下一个调用过来，能使得字符串长度合适。然后在统一发送请求去合成语音，这个思路大概也就是题主的想法。但是这个思路还有一些问题，首先，TTS引擎什么时候取出下一个合成请求并调用service，这个我暂时还没看，猜测一下，要么是负责合成的方法（onSynthesizeText）运行结束，要么就是回调类调用了callback.done()方法。如果是第一种，那这种思路就没有办法了，等不到下一个调用，因为几次调用都是在一个线程上的。如果是第二种，那也非常的麻烦。

**Comment by WeihuaGu** [comment]
@thredreams 
> 另一个就是在service中检查本次合成的字符串的长度，如果过短，就等待很短的一个时间，看有没有下一个调用过来，能使得字符串长度合适。

我也不懂，瞎说，觉得能不能题供两种服务，一种真服务，一种假服务。调用形式完全一样。不检测句字长短，只维护一个等待队列的大小。队头调用一次真服务，且开始在队満前调用假服务，队満后调用一次真服务。

**Comment by lenghun** [comment]
这个应该是播放软件那边去处理的
