### ISSUE TITLE
音频流格式突发不支持

### ISSUE THREAD

**Issue by MogekovHashaski** [ag2s20150909/TTS#78]
使用过程中突然出现output格式不支持，且大多数音频流皆有此情况，包括一直以来使用的音频流。
During the use got error output as `Unsupported output format: <<name (i.e. raw-16khz-16bit-mono-pcm)>>`. Most of the options will get this result, containing the used ones too.
Also will get response like `Send ping but didn't receive pong within 20000ms`, as in issue #77

**Comment by MogekovHashaski** [comment]
另外，我设备上仅存的可用选项是`webm-24khz-16bit-mono-opus`，但是使用过程中偶尔会有奇怪的卡顿，尤其是熄屏后。
In addition, the only usable option on my device for now is `webm-24khz-16bit-mono-opus`, but during the use may occasionally get weird laggings, especially after I lock the screen.

**Comment by wxxxcxx** [comment]
你是什么网络环境啊？

我今天测试API，发现我家里和腾讯云支持所有选项。

**但是在亚马逊云和Oracle云的服务器上测试发现只支持 `webm-24khz-16bit-mono-opus` 这个格式了。**

**Comment by MogekovHashaski** [comment]
具体还真不清楚，是在俄用移动数据连接的

**Comment by wxxxcxx** [comment]
估计就是地区原因了，我的亚马逊云和Oracle云的服务器都在国外。

国内我自己的电脑和腾讯云测试都支持所有音频格式。

折腾一天了，搞死我了，一模一样的代码放服务器上就是跑不起来。。😭

**Comment by MogekovHashaski** [comment]
嗯…… 好的，谢谢告知
我之后也想办法试试看其他服务器吧，如果手头的有有效的会关掉这个issue

**Comment by thredreams** [comment]
我在今天早上遇到了同样的问题。昨晚还没事。

> 估计就是地区原因了，我的亚马逊云和Oracle云的服务器都在国外。
> 
> 国内我自己的电脑和腾讯云测试都支持所有音频格式。
> 
> 折腾一天了，搞死我了，一模一样的代码放服务器上就是跑不起来。。😭

可能并不是，坐标江苏，和他一样，只有`webm-24khz-16bit-mono-opu`有效

**Comment by wxxxcxx** [comment]
> 可能并不是，坐标江苏，和他一样，只有`webm-24khz-16bit-mono-opu`有效

是的，我这也不行了。

另外我测试除了 `webm-24khz-16bit-mono-opu` ，`audio-24khz-48kbitrate-mono-mp3` 和 `audio-24khz-96kbitrate-mono-mp3` 也还可以继续使用。

**Comment by jl0476** [comment]
辽宁也不行了

**Comment by garriton** [comment]
> 我在今天早上遇到了同样的问题。昨晚还没事。
> 
> > 估计就是地区原因了，我的亚马逊云和Oracle云的服务器都在国外。
> > 国内我自己的电脑和腾讯云测试都支持所有音频格式。
> > 折腾一天了，搞死我了，一模一样的代码放服务器上就是跑不起来。。😭
> 
> 可能并不是，坐标江苏，和他一样，只有`webm-24khz-16bit-mono-opu`有效

同江苏，寄了

**Comment by MogekovHashaski** [comment]
于版本`TTS_release_v0.2_202207172126`调整至普通模式音频仅支持前三个，故此关闭。
