### ISSUE TITLE
建议增加词典的使用说明

### ISSUE THREAD

**Issue by Hoinjjj** [ag2s20150909/TTS#82]
虽然默认有两行范例，但是当我输入沉着脸=chen 2 zhe 0 lian 3 时发现朗读时会跳过这一段（而且我也不知道轻音怎么标注）
另外，正常的四声调也会有这样的情况出现。

**Comment by ag2s20150909** [comment]
https://docs.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-ssml-phonetic-sets#tone

**Comment by Hoinjjj** [comment]
感谢

**Comment by zycboss** [comment]
轻音是 5
你设定了错误的词典就会导致卡住或者跳过这一句
另外要考虑到词典内部规则不要互相冲突，要不然也会卡住
