### ISSUE TITLE
报错：Expected HTTP 101 response but was '401 Unauthorized'

### ISSUE THREAD

**Issue by 2ciyv** [ag2s20150909/TTS#88]
发生错误：Expected HTTP 101 response but
was '401 Unauthorized'

**Comment by chenyajunai** [comment]
> 发生错误：Expected HTTP 101 response but was '401 Unauthorized'

28号晚上就用不了了，29号下午5点多忽然正常了

**Comment by suiahae** [comment]
最近我这边也经常出现这个报错

**Comment by BHBJT** [comment]
> 发生错误：Expected HTTP 101 response but was '401 Unauthorized'

基本上使用三五分钟就会出现这个错误

**Comment by suiahae** [comment]
估计与网络环境有关，我这WiFi无法使用，切换手机卡流量正常。**但我不清楚为什么WiFi无法使用，以及如何解决。**
下面是一些发现，希望有所帮助。

> 查看[源码](https://github.com/ag2s20150909/TTS/blob/master/app/src/main/java/me/ag2s/tts/services/TokenHolder.java#L59)发现软件预览语音借用的是 [Azure 文字转语音演示应用]，地址：
> https://azure.microsoft.com/zh-cn/services/cognitive-services/text-to-speech/
> 
> 在报此错误的网络环境下，用浏览器访问链接会得到 Azure error: Your request timed out
> ![图片](https://user-images.githubusercontent.com/45323123/181877107-7b9477fe-241d-4b07-a48b-13bdcffecf7f.png)
>

**Comment by 8482** [comment]
我的网络除了非预览的晓晓外都容易出现报错
https://azure.microsoft.com/zh-tw/services/cognitive-services/text-to-speech/#features 报错网络环境下，zh-tw 能正常打开，
zh-cn 出现Azure error: Your request timed out

希望这些能有所帮助

**Comment by lmst2** [comment]
杀掉内存重新启动，多次之后会回复正常，但是隔五分钟左右又会重新出现这个问题。播放的时候如果暂停那再播放的时候就会再次出现这个问题。使用的是云野，默认，第一个默认音频流。
