### ISSUE TITLE
2022/9/1 今天突然用不了了

### ISSUE THREAD

**Issue by zycboss** [ag2s20150909/TTS#97]
华为P30

没有更改任何设置，昨天还是正常
今天完全无法朗读，预览也没声音
杀进程，重启手机，换音频格式，换网络环境，都无效
考虑到是到月初了，是不是什么东西过期了？

**Comment by 1753851153** [comment]
是这样，mate20也用不了了

**Comment by XYL161027** [comment]
一样用不了

**Comment by fdn506** [comment]
mate30pro今天开始也用不了了

**Comment by ledong1** [comment]
确实用不了了

**Comment by 2966627080** [comment]
也是一样用不了了，

**Comment by fdn506** [comment]
楼上你们都是啥手机，我怀疑是不是只有华为用不了了 @ledong1 @XYL161027 @2966627080

**Comment by xuzitian2008** [comment]
并不是，我红米也用不了。

**Comment by 2966627080** [comment]
兄弟们，我发现把预览关了就毛事没有了，就是不能选语气了

**Comment by chenyajunai** [comment]
好像是官网也错误，提示加载此演示时发生错误，请重载并重试

**Comment by fdn506** [comment]
按楼上提供的办法试了下，可以用晓晓和云杨，选别的就不行了

**Comment by zycboss** [comment]
> 按楼上提供的办法试了下，可以用晓晓和云杨，选别的就不行了

去官网上试了下，发现现在也是只有晓晓和云杨可以选风格了，其他的风格菜单都是灰色的，不知道是不是巨硬故意关掉的
https://azure.microsoft.com/en-us/services/cognitive-services/text-to-speech/#features

**Comment by lmst2** [comment]
兄弟们，我找到了一个暂时替代的方法，如果你们用的是 [阅读（legado）](https://github.com/gedoor/legado) 来听小说的话，你们可以用这个repo https://github.com/wxxxcxx/ms-ra-forwarder 
直接按照这个步骤走
Docker
需要安装 docker。

#### 拉取镜像
`docker pull meetcw/ms-ra-forwarder:latest`
#### 运行
`docker run --name ms-ra-forwarder -d -p 3000:3000 meetcw/ms-ra-forwarder`
#### 浏览器访问 http://localhost:3000
![image](https://user-images.githubusercontent.com/29498103/188239338-820c574d-bdcc-4a94-a5ce-eda41c2e9ed9.png)
![image](https://user-images.githubusercontent.com/29498103/188239431-5b90b408-6a98-41dd-aca2-88ba7d18a464.png)

完成之后电脑上用ipconfig之类的命令查看一下你电脑的局域网IP，把上面链接里的localhost改成你电脑的IP，手机电脑在同一个WiFi下就可以听小说了。
进阶的玩法是，本地运行之后用[zeroiter](https://my.zerotier.com/)把手机和电脑之间建立局域网，之后就可以在外面使用流量听小说了，只不过这个IP要在zeroiter的里面查看。

**Comment by jing332** [comment]
可以部署到 Railway，更方便，不需要自己挂着服务端
https://ms-ra-forwarder-production-876a.up.railway.app

**Comment by jing332** [comment]
> 兄弟们，我找到了一个暂时替代的方法，如果你们用的是 [阅读（legado）](https://github.com/gedoor/legado) 来听小说的话，你们可以用这个repo https://github.com/wxxxcxx/ms-ra-forwarder 直接按照这个步骤走 Docker 需要安装 docker。
> 
> #### 拉取镜像
> `docker pull meetcw/ms-ra-forwarder:latest`
> 
> #### 运行
> `docker run --name ms-ra-forwarder -d -p 3000:3000 meetcw/ms-ra-forwarder`
> 
> #### 浏览器访问 http://localhost:3000
> ![image](https://user-images.githubusercontent.com/29498103/188239338-820c574d-bdcc-4a94-a5ce-eda41c2e9ed9.png) ![image](https://user-images.githubusercontent.com/29498103/188239431-5b90b408-6a98-41dd-aca2-88ba7d18a464.png)
> 
> 完成之后电脑上用ipconfig之类的命令查看一下你电脑的局域网IP，把上面链接里的localhost改成你电脑的IP，手机电脑在同一个WiFi下就可以听小说了。 进阶的玩法是，本地运行之后用[zeroiter](https://my.zerotier.com/)把手机和电脑之间建立局域网，之后就可以在外面使用流量听小说了，只不过这个IP要在zeroiter的里面查看。

可以部署到 Railway，更方便，不需要自己挂着服务端
https://ms-ra-forwarder-production-876a.up.railway.app
另外我又发现个国内的接口https://tts.quickso.cn/api/ra
直接替换url就可以用
![Screenshot_20220903-075512648](https://user-images.githubusercontent.com/42014615/188247464-d0e777e4-0026-4ee0-8853-2465a990964c.jpg)

**Comment by lmst2** [comment]
> 可以部署到 Railway，更方便，不需要自己挂着服务端 https://ms-ra-forwarder-production-876a.up.railway.app

railway 免费额度太小了，而且是持续算时间的，不到一个月就用不了了，还是自己搭省心，有个台式机很方便的

**Comment by rebron1900** [comment]
> > 可以部署到 Railway，更方便，不需要自己挂着服务端 https://ms-ra-forwarder-production-876a.up.railway.app
> 
> railway 免费额度太小了，而且是持续算时间的，不到一个月就用不了了，还是自己搭省心，有个台式机很方便的

railway是按CPU、内存占用来算的，这ms-ra-forwarder只是请求转发，消耗的都是流量，基本上用不上什么cpu和内存，提供的免费额度基本上你每天24小时听都不会超额。

**Comment by lmst2** [comment]
> > > 可以部署到 Railway，更方便，不需要自己挂着服务端 https://ms-ra-forwarder-production-876a.up.railway.app
> > 
> > 
> > railway 免费额度太小了，而且是持续算时间的，不到一个月就用不了了，还是自己搭省心，有个台式机很方便的
> 
> railway是按CPU、内存占用来算的，这ms-ra-forwarder只是请求转发，消耗的都是流量，基本上用不上什么cpu和内存，提供的免费额度基本上你每天24小时听都不会超额。

我一开始也是这么想的，我部署了之后只用了两天，然后九月一号准备临时救急来着，结果发现连不上了，打开一看说我运行时长超了
![image](https://user-images.githubusercontent.com/29498103/188256038-97aff143-3232-4bdf-ba61-20c179a6b3b1.png)
你看这个免费版只要500小时运行时间。我前面看了一下发现我的免费5刀额度只用了0.05刀。然后说我的运行时长超过589小时超过免费额度，早就给我停了。所以我就之间自己台式机上搭了一个，不用担心流量，也没有运行时长限制

这个不像是阿里云那种弹性function，只在调用的时候才会运行特定函数，这个应该是程序本体一直在监听3000端口，这样就相当于程序一直在运行，那500小时也就大半个月，月底就用不了了。

**Comment by rebron1900** [comment]
> > > > 可以部署到 Railway，更方便，不需要自己挂着服务端 https://ms-ra-forwarder-production-876a.up.railway.app
> > > 
> > > 
> > > railway 免费额度太小了，而且是持续算时间的，不到一个月就用不了了，还是自己搭省心，有个台式机很方便的
> > 
> > 
> > railway是按CPU、内存占用来算的，这ms-ra-forwarder只是请求转发，消耗的都是流量，基本上用不上什么cpu和内存，提供的免费额度基本上你每天24小时听都不会超额。
> 
> 我一开始也是这么想的，我部署了之后只用了两天，然后九月一号准备临时救急来着，结果发现连不上了，打开一看说我运行时长超了 ![image](https://user-images.githubusercontent.com/29498103/188256038-97aff143-3232-4bdf-ba61-20c179a6b3b1.png) 你看这个免费版只要500小时运行时间。我前面看了一下发现我的免费5刀额度只用了0.05刀。然后说我的运行时长超过589小时超过免费额度，早就给我停了。所以我就之间自己台式机上搭了一个，不用担心流量，也没有运行时长限制
> 
> 这个不像是阿里云那种弹性function，只在调用的时候才会运行特定函数，这个应该是程序本体一直在监听3000端口，这样就相当于程序一直在运行，那500小时也就大半个月，月底就用不了了。

你绑信用卡没？Railway前段时间免费制度改了，现在必须要绑定信用卡成为开发者订阅才会有免费5刀+无运行时间限制。

![image](https://user-images.githubusercontent.com/7929884/188258353-ba55bece-c8f4-4194-90ae-855264fdcdb1.png)

**Comment by lmst2** [comment]
> > > > > 可以部署到 Railway，更方便，不需要自己挂着服务端 https://ms-ra-forwarder-production-876a.up.railway.app
> > > > 
> > > > 
> > > > railway 免费额度太小了，而且是持续算时间的，不到一个月就用不了了，还是自己搭省心，有个台式机很方便的
> > > 
> > > 
> > > railway是按CPU、内存占用来算的，这ms-ra-forwarder只是请求转发，消耗的都是流量，基本上用不上什么cpu和内存，提供的免费额度基本上你每天24小时听都不会超额。
> > 
> > 
> > 我一开始也是这么想的，我部署了之后只用了两天，然后九月一号准备临时救急来着，结果发现连不上了，打开一看说我运行时长超了 ![image](https://user-images.githubusercontent.com/29498103/188256038-97aff143-3232-4bdf-ba61-20c179a6b3b1.png) 你看这个免费版只要500小时运行时间。我前面看了一下发现我的免费5刀额度只用了0.05刀。然后说我的运行时长超过589小时超过免费额度，早就给我停了。所以我就之间自己台式机上搭了一个，不用担心流量，也没有运行时长限制
> > 这个不像是阿里云那种弹性function，只在调用的时候才会运行特定函数，这个应该是程序本体一直在监听3000端口，这样就相当于程序一直在运行，那500小时也就大半个月，月底就用不了了。
> 
> 你绑信用卡没？Railway前段时间免费制度改了，现在必须要绑定信用卡成为开发者订阅才会有免费5刀+无运行时间限制。
> 
> ![image](https://user-images.githubusercontent.com/7929884/188258353-ba55bece-c8f4-4194-90ae-855264fdcdb1.png)

哦有这规定，我没注意到，那这就说得通了。我没有绑卡
